apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: redis-queue
spec:
  selector:
    matchLabels:
      service: redis-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: redis-queue
    spec:
      hostAliases:
      - ip: "52.89.65.81"
        hostnames:
        - "asp.eksv21.deepfactor.io"
      containers:
      - env:
        image: redis
        name: redis-queue
        ports:
        - containerPort: 6379
      restartPolicy: Always
