apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: users-api
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: users-api
      annotations:
        df.k8-app.comp.users-api/alertPolicy: "bip-max"
        df.k8-app.comp.users-api/lsa: "java"
    spec:
      hostAliases:
      - ip: "52.89.65.81"
        hostnames:
        - "asp.eksv21.deepfactor.io"
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: SERVER_PORT
          value: "8083"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://zipkin:9411
        image: deepfactor/todo-app-users-api:anurag
        name: users-api
        ports:
        - containerPort: 8083
        imagePullPolicy: Never
      restartPolicy: Always
